Setup/capybara
Theodoraldo/blog pull request #8
Opened 2023-10-01 17:45 UTC by Theodoraldo

### At this stage, I:
- Write integration tests with Capybara gem.
- Secure app from n+1 problems.

2023-10-02 19:11 UTC, Shedrack-Sunday requested changes
Hello @Theodoraldo          👋 

# CHANGES REQUIRED ♻️

Impressive work on the project so far👏
You've done extremely well so far in this project,  However, there are some adjustments you need to make to move to the next project. 💯

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- Good use of GitHub features ✔️   
- Nice work with the Rails features ✔️
- Moderate use of Capybara testing features ✔️  

# Required Changes  🌵  

- [x] You did not include the requirement for N+1 problem,  when fetching all posts and their comments for a user.  Kindly use this [Article](https://dev.to/junko911/rails-n-1-queries-and-eager-loading-10eh) as a guide. 
### Your  current fetching code :
![image](https://github.com/Theodoraldo/blog/assets/50990925/ac612b9b-4212-4f57-ab18-a2a93dc8ba82)


- Make sure to add the query log not the run time code run 👍 

_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing really improves your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-10-03 03:54 UTC, FrederickMih requested changes
## Hi :raising_hand: :raising_hand: @Theodoraldo , 


Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Highlights :green_circle: 

- Unit tests are running with success :+1: 


## Required Changes ♻️
**N/A**
_Check the comments under the review._

## Optional suggestions
**N/A**
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-03 03:54 UTC, FrederickMih commented on app/controllers/posts_controller.rb
> +    @posts = @user.posts.preload(:comments)
- [ ] ActiveRecord provides an awesome method called `includes` which eager load association in a smarter way and prevents N+1 queries issues. We are still fetching the comments of each posts which still leads to the N+1 queries problems as you can see below. This problem can be resolve using includes methods: `@user.posts.includes(:comments)`

![Screenshot from 2023-10-03 04-49-27](https://github.com/Theodoraldo/blog/assets/63087491/6a132fda-7607-4092-bba4-729ec571d34f)

2023-10-03 04:15 UTC, Shedrack-Sunday approved these changes
Hi @Theodoraldo 

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![image](https://github.com/krisbobo/blog-app/assets/50990925/76d09bb1-9dc7-46c0-be49-31f366afa4b8)


Highlights
- [x] Good project organization ✔️
- [x] Nice use of Rails testing features ✔️  
- [x] Kudus on meeting the requirements as  required  ✔️


Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-10-03 07:01 UTC, merged